matrix: 
  include: 
  - os: linux
    name: "Systemtests"
    if: fork = false AND ( branch = master OR branch = develop )
    python: "3.6" 
    env: PY=python3
    script:
    - curl -LO --retry 3 https://raw.githubusercontent.com/precice/systemtests/develop/trigger_systemtests.py
    - travis_wait 60 $PY trigger_systemtests.py --adapter fenics --wait

